-- Supabase schema for inspection_system.html
-- Run this in Supabase SQL Editor after creating a new project.

create extension if not exists "pgcrypto";

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'partner')),
  display_name text not null,
  partner_id bigint,
  created_at timestamptz not null default now()
);

create table public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text,
  color text not null default '#1A9E72',
  created_at timestamptz not null default now()
);

alter table public.profiles
  add constraint profiles_partner_id_fkey
  foreign key (partner_id) references public.partners(id) on delete set null;

create table public.jobs (
  id bigint generated by default as identity primary key,
  partner_id bigint not null references public.partners(id) on delete restrict,
  name text not null,
  request_date date not null,
  due_date date,
  maker text,
  sku text,
  sizes jsonb not null default '[]'::jsonb,
  total integer not null default 0 check (total >= 0),
  done integer not null default 0 check (done >= 0),
  work_type text not null default '検品・たたみ',
  detail text,
  instruction text,
  status text not null default '進行中'
    check (status in ('進行中', '検品済確認中', '一時停止', '完了')),
  checked_at date,
  completed_at date,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_reports (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  partner_id bigint not null references public.partners(id) on delete restrict,
  report_date date not null default current_date,
  count integer not null default 0 check (count >= 0),
  note text,
  report_type text not null check (report_type in ('progress', 'checked', 'final')),
  created_at timestamptz not null default now()
);

create table public.b_reports (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  partner_id bigint not null references public.partners(id) on delete restrict,
  report_date date not null default current_date,
  cats text[] not null default '{}',
  description text not null,
  size text,
  images jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'B品', '良品')),
  judge_comment text,
  faq_public boolean not null default false,
  judged_at date,
  created_at timestamptz not null default now()
);

create table public.faqs (
  id bigint generated by default as identity primary key,
  cats text[] not null default '{}',
  question text not null,
  answer text not null,
  images jsonb not null default '[]'::jsonb,
  source_report_id bigint references public.b_reports(id) on delete set null,
  created_at date not null default current_date
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger jobs_touch_updated_at
before update on public.jobs
for each row execute function public.touch_updated_at();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.my_partner_id()
returns bigint language sql stable security definer set search_path = public as $$
  select partner_id from public.profiles where id = auth.uid();
$$;

alter table public.profiles enable row level security;
alter table public.partners enable row level security;
alter table public.jobs enable row level security;
alter table public.job_reports enable row level security;
alter table public.b_reports enable row level security;
alter table public.faqs enable row level security;

create policy "profiles read own or admin"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

create policy "profiles admin write"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "partners read own or admin"
on public.partners for select
using (public.is_admin() or id = public.my_partner_id());

create policy "partners admin write"
on public.partners for all
using (public.is_admin())
with check (public.is_admin());

create policy "jobs read own or admin"
on public.jobs for select
using (public.is_admin() or partner_id = public.my_partner_id());

create policy "jobs admin write"
on public.jobs for all
using (public.is_admin())
with check (public.is_admin());

create policy "jobs partner progress update"
on public.jobs for update
using (partner_id = public.my_partner_id())
with check (partner_id = public.my_partner_id());

create policy "job reports read own or admin"
on public.job_reports for select
using (public.is_admin() or partner_id = public.my_partner_id());

create policy "job reports insert own or admin"
on public.job_reports for insert
with check (public.is_admin() or partner_id = public.my_partner_id());

create policy "b reports read own or admin"
on public.b_reports for select
using (public.is_admin() or partner_id = public.my_partner_id());

create policy "b reports insert own or admin"
on public.b_reports for insert
with check (public.is_admin() or partner_id = public.my_partner_id());

create policy "b reports admin update"
on public.b_reports for update
using (public.is_admin())
with check (public.is_admin());

create policy "faqs readable by signed in users"
on public.faqs for select
using (auth.uid() is not null);

create policy "faqs admin write"
on public.faqs for all
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'inspection-images',
  'inspection-images',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do nothing;

create policy "inspection images readable by signed in users"
on storage.objects for select
using (bucket_id = 'inspection-images' and auth.uid() is not null);

create policy "inspection images upload by signed in users"
on storage.objects for insert
with check (bucket_id = 'inspection-images' and auth.uid() is not null);

create policy "inspection images admin delete"
on storage.objects for delete
using (bucket_id = 'inspection-images' and public.is_admin());

